### ISSUE TITLE
Add Kip to website

### ISSUE THREAD

**Issue by esmyers** [USGS-WiM/WIM-Main-Site#108]
Kip,

- [x] Draft a bio for the WIM Website & provide headshot (can provide content in a comment)

- [x] Once complete, assign to Mitch (mitchas)

Mitch,

- [x] Add Kip to website

**Comment by KipSullivan** [comment]
![kip](https://user-images.githubusercontent.com/76274215/120700628-81a29400-c477-11eb-9eab-0a4fbb272352.jpg)

Kip is currently a student at the University of Wisconsin-Madison pursuing a bachelor's degree in Computer Engineering and Computer Science with a certificate in Criminal Justice. Kip has been programming since middle school and has developed many individual programming projects before joining WIM, including applications for both desktop and mobile devices. His other interests include golfing, learning guitar, and working on cars.
