### ISSUE TITLE
Add Nathan & Mackenzie to the team page

### ISSUE THREAD

**Issue by HansVraga** [USGS-WiM/WIM-Main-Site#69]

**Comment by HansVraga** [comment]
@Kenzie-Meni and @NathanKrawza Can you write up some "blurbs" similar to what's already on the site, and add them to the issue here?

**Comment by Kenzie-Meni** [comment]
Mackenzie is a junior developer for WIM. She is currently working towards a B.S in Mathematics with a Minor in Engineering Physics at McKendree University. Mackenzie loves everything math and has recently entered the world of coding. Although she spends the majority of her time working or at school, she enjoys playing coed soccer, volunteering, and spending time with her family.

**Comment by NathanKrawza** [comment]
Nathan is a student developer for WIM. He is studying Management Information Systems at the Carlson School of Management, University of Minnesota. He built his first computer in the 7th grade and has had a passion for computers and technology ever since. Nathan's previous experiences include being a computer sales associate at Best Buy, a camp counselor, and a grocery bagger. He enjoys going for runs, playing multiple rhythm instruments, traveling, and driving his stick-shift 2001 Honda Accord.
